version: "3.8"

services:
  # backend:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mysql
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_DB: kitaleicht

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
